### ISSUE TITLE
Tee.Format.pas

### ISSUE THREAD

**Issue by TomYU6** [Steema/TeeGrid#2]
The code is incomplete and can not be compiled.
I tried to download the TeeGrid-master.zip file and TeeGrid-1.0-rc.exe.

**Comment by mogmem** [comment]
The RC version is binary; installable but not compilable. The TeeGrid-Master contains interface definitions only. The latest Beta is still available as sourcecode, you can see a link to it on this page:
[https://github.com/Steema/TeeGrid/wiki/2.-Installation](url)
