### ISSUE TITLE
all source code files incomplete

### ISSUE THREAD

**Issue by chris9672** [Steema/TeeGrid#5]
All source code files end with
"**implementation**".
The mandatory "**end.**" Is missing in all files. 
![01-02-_2021_12-40-19](https://user-images.githubusercontent.com/55849038/106454365-ea0e4400-648a-11eb-97a6-3253cd5b09e5.png)

**Comment by YerayAlonso** [comment]
The code in this repo contains interface definitions only. Find the latest version available at the link below:
https://github.com/Steema/TeeGrid/wiki/2.-Installation
